import hashlib
import os
import re

MAX_SLIDER_LENGTH = 500.0

def get_file_content_md5(file_path):
    """
    Calculate the MD5 checksum of the actual .osu file contents.
    """
    md5 = hashlib.md5()
    with open(file_path, "rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            md5.update(chunk)

    return md5.hexdigest()

def build_osu_file_index(root_dir, conn):
    """
    Build local .osu file lookup tables using the database as the
    source of truth for beatmap identity.

    Returns:

        by_beatmap_id:
            beatmap_id -> local .osu filepath

        by_md5:
            file-content MD5 -> local .osu filepath

    The database must contain:

        beatmap_id
        md5

    This means old .osu files do not need to contain BeatmapID.
    """
    by_beatmap_id = {}
    by_md5 = {}

    # Regex to match duplicate suffixes like _1.osu, _2.osu, etc. before the extension
    duplicate_pattern = re.compile(r'_\d+\.osu$', re.IGNORECASE)

    osu_files = []
    for dirpath, _, filenames in os.walk(root_dir):
        for filename in filenames:
            if not filename.lower().endswith(".osu"):
                continue

            # Skip duplicate files generated by downloaders (e.g., _1.osu, _2.osu)
            if duplicate_pattern.search(filename):
                continue

            file_path = os.path.join(dirpath, filename)
            osu_files.append(file_path)

    print(f"Found {len(osu_files):,} local .osu files.")

    for i, file_path in enumerate(osu_files, start=1):
        try:
            checksum = get_file_content_md5(file_path)

            if checksum in by_md5:
                print(
                    f"Warning: duplicate MD5:\n"
                    f"  Existing: {by_md5[checksum]}\n"
                    f"  New:      {file_path}\n"
                    f"  MD5:      {checksum}"
                )
            else:
                by_md5[checksum] = file_path

        except Exception as e:
            print(f"Warning: failed to hash {file_path}: {type(e).__name__}: {e}")

        if i % 5000 == 0:
            print(f"Indexed {i:,}/{len(osu_files):,} files")

    # ------------------------------------------------------------
    # Use DB beatmap_id -> md5 mapping to build numeric lookup
    # ------------------------------------------------------------

    cursor = conn.execute("""
        SELECT beatmap_id, md5
        FROM beatmaps
        WHERE md5 IS NOT NULL
    """)

    db_rows = cursor.fetchall()

    missing_local_files = []
    matched_beatmaps = 0

    for beatmap_id, md5 in db_rows:
        beatmap_id = str(beatmap_id)
        file_path = by_md5.get(md5)
        if file_path is None:
            missing_local_files.append((beatmap_id, md5))
            continue

        by_beatmap_id[beatmap_id] = file_path
        matched_beatmaps += 1

    # ------------------------------------------------------------
    # Diagnostics
    # ------------------------------------------------------------

    print()
    print("Local file index complete.")
    print(f"  Files scanned:        {len(osu_files):,}")
    print(f"  MD5 identifiers:      {len(by_md5):,}")
    print(f"  DB beatmaps:          {len(db_rows):,}")
    print(f"  Beatmaps with files:  {matched_beatmaps:,}")
    print(f"  Missing local files:  {len(missing_local_files):,}")

    if missing_local_files:
        print()
        print("Examples of DB beatmaps with no local file:")

        for beatmap_id, md5 in missing_local_files[:20]:
            print(f"  Beatmap ID: {beatmap_id}")
            print(f"  MD5:        {md5}")

    print()

    return by_beatmap_id, by_md5