SELECT
    variant_id,
    nm1, nm2, nm3, nm4, nm5, nm6,
    dt1, dt2_and_dt3, dt4,
    hr1, hr2, hr3,
    hd1, hd2, hd3,
    tiebreaker
FROM tournament_predictions
WHERE
    (CASE WHEN nm1 IS NOT NULL THEN 1 ELSE 0 END +
     CASE WHEN nm2 IS NOT NULL THEN 1 ELSE 0 END +
     CASE WHEN nm3 IS NOT NULL THEN 1 ELSE 0 END +
     CASE WHEN nm4 IS NOT NULL THEN 1 ELSE 0 END +
     CASE WHEN nm5 IS NOT NULL THEN 1 ELSE 0 END +
     CASE WHEN nm6 IS NOT NULL THEN 1 ELSE 0 END +
     CASE WHEN dt1 IS NOT NULL THEN 1 ELSE 0 END +
     CASE WHEN dt2_and_dt3 IS NOT NULL THEN 1 ELSE 0 END +
     CASE WHEN dt4 IS NOT NULL THEN 1 ELSE 0 END +
     CASE WHEN hr1 IS NOT NULL THEN 1 ELSE 0 END +
     CASE WHEN hr2 IS NOT NULL THEN 1 ELSE 0 END +
     CASE WHEN hr3 IS NOT NULL THEN 1 ELSE 0 END +
     CASE WHEN hd1 IS NOT NULL THEN 1 ELSE 0 END +
     CASE WHEN hd2 IS NOT NULL THEN 1 ELSE 0 END +
     CASE WHEN hd3 IS NOT NULL THEN 1 ELSE 0 END +
     CASE WHEN tiebreaker IS NOT NULL THEN 1 ELSE 0 END) >= 2;