"""
MIT License

Copyright (c) 2026-Present O!Lib Contributors

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
"""

from . import _patches
from .acronym import Acronym
from .game_mod import GameMod
from .game_mod_intermode import GameModIntermode
from .game_mod_kind import GameModKind
from .game_mod_simple import GameModSimple, SettingSimple
from .game_mode import GameMode
from .game_mods import GameMods
from .game_mods_intermode import GameModsIntermode
from .game_mods_legacy import GameModsLegacy
from .generated_mods import (
    AccuracyChallengeCatch,
    AccuracyChallengeMania,
    AccuracyChallengeOsu,
    AccuracyChallengeTaiko,
    AdaptiveSpeedMania,
    AdaptiveSpeedOsu,
    AdaptiveSpeedTaiko,
    AlternateOsu,
    ApproachDifferentOsu,
    AutopilotOsu,
    AutoplayCatch,
    AutoplayMania,
    AutoplayOsu,
    AutoplayTaiko,
    BarrelRollOsu,
    BlindsOsu,
    BloomOsu,
    BubblesOsu,
    CinemaCatch,
    CinemaMania,
    CinemaOsu,
    CinemaTaiko,
    ClassicCatch,
    ClassicMania,
    ClassicOsu,
    ClassicTaiko,
    ConstantSpeedMania,
    ConstantSpeedTaiko,
    CoverMania,
    DaycoreCatch,
    DaycoreMania,
    DaycoreOsu,
    DaycoreTaiko,
    DeflateOsu,
    DepthOsu,
    DifficultyAdjustCatch,
    DifficultyAdjustMania,
    DifficultyAdjustOsu,
    DifficultyAdjustTaiko,
    DoubleTimeCatch,
    DoubleTimeMania,
    DoubleTimeOsu,
    DoubleTimeTaiko,
    DualStagesMania,
    EasyCatch,
    EasyMania,
    EasyOsu,
    EasyTaiko,
    EightKeysMania,
    FadeInMania,
    FiveKeysMania,
    FlashlightCatch,
    FlashlightMania,
    FlashlightOsu,
    FlashlightTaiko,
    FloatingFruitsCatch,
    FourKeysMania,
    FreezeFrameOsu,
    GrowOsu,
    HalfTimeCatch,
    HalfTimeMania,
    HalfTimeOsu,
    HalfTimeTaiko,
    HardRockCatch,
    HardRockMania,
    HardRockOsu,
    HardRockTaiko,
    HiddenCatch,
    HiddenMania,
    HiddenOsu,
    HiddenTaiko,
    HoldOffMania,
    InvertMania,
    MagnetisedOsu,
    MirrorCatch,
    MirrorMania,
    MirrorOsu,
    MovingFastCatch,
    MutedCatch,
    MutedMania,
    MutedOsu,
    MutedTaiko,
    NightcoreCatch,
    NightcoreMania,
    NightcoreOsu,
    NightcoreTaiko,
    NineKeysMania,
    NoFailCatch,
    NoFailMania,
    NoFailOsu,
    NoFailTaiko,
    NoReleaseMania,
    NoScopeCatch,
    NoScopeOsu,
    OneKeyMania,
    PerfectCatch,
    PerfectMania,
    PerfectOsu,
    PerfectTaiko,
    RandomMania,
    RandomOsu,
    RandomTaiko,
    RelaxCatch,
    RelaxOsu,
    RelaxTaiko,
    RepelOsu,
    ScoreV2Catch,
    ScoreV2Mania,
    ScoreV2Osu,
    ScoreV2Taiko,
    SevenKeysMania,
    SimplifiedRhythmTaiko,
    SingleTapOsu,
    SingleTapTaiko,
    SixKeysMania,
    SpinInOsu,
    SpunOutOsu,
    StrictTrackingOsu,
    SuddenDeathCatch,
    SuddenDeathMania,
    SuddenDeathOsu,
    SuddenDeathTaiko,
    SwapTaiko,
    SynesthesiaOsu,
    TargetPracticeOsu,
    TenKeysMania,
    ThreeKeysMania,
    TouchDeviceOsu,
    TraceableOsu,
    TransformOsu,
    TwoKeysMania,
    UnknownMod,
    WiggleOsu,
    WindDownCatch,
    WindDownMania,
    WindDownOsu,
    WindDownTaiko,
    WindUpCatch,
    WindUpMania,
    WindUpOsu,
    WindUpTaiko,
)

__all__ = [
    "GameMode",
    "GameModKind",
    "Acronym",
    "GameMod",
    "GameMods",
    "GameModIntermode",
    "GameModsIntermode",
    "GameModsLegacy",
    "GameModSimple",
    "SettingSimple",
    "EasyOsu",
    "NoFailOsu",
    "HalfTimeOsu",
    "DaycoreOsu",
    "HardRockOsu",
    "SuddenDeathOsu",
    "PerfectOsu",
    "DoubleTimeOsu",
    "NightcoreOsu",
    "HiddenOsu",
    "TraceableOsu",
    "FlashlightOsu",
    "BlindsOsu",
    "StrictTrackingOsu",
    "AccuracyChallengeOsu",
    "TargetPracticeOsu",
    "DifficultyAdjustOsu",
    "ClassicOsu",
    "RandomOsu",
    "MirrorOsu",
    "AlternateOsu",
    "SingleTapOsu",
    "AutoplayOsu",
    "CinemaOsu",
    "RelaxOsu",
    "AutopilotOsu",
    "SpunOutOsu",
    "TransformOsu",
    "WiggleOsu",
    "SpinInOsu",
    "GrowOsu",
    "DeflateOsu",
    "WindUpOsu",
    "WindDownOsu",
    "BarrelRollOsu",
    "ApproachDifferentOsu",
    "MutedOsu",
    "NoScopeOsu",
    "MagnetisedOsu",
    "RepelOsu",
    "AdaptiveSpeedOsu",
    "FreezeFrameOsu",
    "BubblesOsu",
    "SynesthesiaOsu",
    "DepthOsu",
    "BloomOsu",
    "TouchDeviceOsu",
    "ScoreV2Osu",
    "EasyTaiko",
    "NoFailTaiko",
    "HalfTimeTaiko",
    "DaycoreTaiko",
    "SimplifiedRhythmTaiko",
    "HardRockTaiko",
    "SuddenDeathTaiko",
    "PerfectTaiko",
    "DoubleTimeTaiko",
    "NightcoreTaiko",
    "HiddenTaiko",
    "FlashlightTaiko",
    "AccuracyChallengeTaiko",
    "RandomTaiko",
    "DifficultyAdjustTaiko",
    "ClassicTaiko",
    "SwapTaiko",
    "SingleTapTaiko",
    "ConstantSpeedTaiko",
    "AutoplayTaiko",
    "CinemaTaiko",
    "RelaxTaiko",
    "WindUpTaiko",
    "WindDownTaiko",
    "MutedTaiko",
    "AdaptiveSpeedTaiko",
    "ScoreV2Taiko",
    "EasyCatch",
    "NoFailCatch",
    "HalfTimeCatch",
    "DaycoreCatch",
    "HardRockCatch",
    "SuddenDeathCatch",
    "PerfectCatch",
    "DoubleTimeCatch",
    "NightcoreCatch",
    "HiddenCatch",
    "FlashlightCatch",
    "AccuracyChallengeCatch",
    "DifficultyAdjustCatch",
    "ClassicCatch",
    "MirrorCatch",
    "AutoplayCatch",
    "CinemaCatch",
    "RelaxCatch",
    "WindUpCatch",
    "WindDownCatch",
    "FloatingFruitsCatch",
    "MutedCatch",
    "NoScopeCatch",
    "MovingFastCatch",
    "ScoreV2Catch",
    "EasyMania",
    "NoFailMania",
    "HalfTimeMania",
    "DaycoreMania",
    "NoReleaseMania",
    "HardRockMania",
    "SuddenDeathMania",
    "PerfectMania",
    "DoubleTimeMania",
    "NightcoreMania",
    "FadeInMania",
    "HiddenMania",
    "CoverMania",
    "FlashlightMania",
    "AccuracyChallengeMania",
    "RandomMania",
    "DualStagesMania",
    "MirrorMania",
    "DifficultyAdjustMania",
    "ClassicMania",
    "InvertMania",
    "ConstantSpeedMania",
    "HoldOffMania",
    "OneKeyMania",
    "TwoKeysMania",
    "ThreeKeysMania",
    "FourKeysMania",
    "FiveKeysMania",
    "SixKeysMania",
    "SevenKeysMania",
    "EightKeysMania",
    "NineKeysMania",
    "TenKeysMania",
    "AutoplayMania",
    "CinemaMania",
    "WindUpMania",
    "WindDownMania",
    "MutedMania",
    "AdaptiveSpeedMania",
    "ScoreV2Mania",
    "UnknownMod",
]
