server {
    listen 80;
    server_name recommendosu.com;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://recommendosu.com$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name recommendosu.com;

    proxy_intercept_errors on;

    ssl_certificate /etc/letsencrypt/live/recommendosu.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/recommendosu.com/privkey.pem;

    location /api/ {
        proxy_pass http://backend:8000;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /docs {
        proxy_pass http://backend:8000;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /openapi.json {
        proxy_pass http://backend:8000;

        proxy_set_header Host $host;
    }

    location / {
        proxy_pass http://frontend:4173;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    error_page 502 503 504 /restarting.html;

    location = /restarting.html {
        root /usr/share/nginx/html;
        internal;
    }

    location = /restarting.gif {
        root /usr/share/nginx/html;
    }
}